In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0.dev20240218+cu121


In [2]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
#vector
vector = torch.tensor([
    [2,3],
    [4,5]
])
vector

tensor([[2, 3],
        [4, 5]])

In [6]:
vector.ndim

2

In [7]:
vector.shape

torch.Size([2, 2])

In [8]:
### Creating range of tensor and tensor-like
one_to_ten = torch.arange(start = 1,end = 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#creating tensorlike
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [10]:
# flaot 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                              device='cuda',
                              requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [11]:
float_32_tensor.dtype

torch.float32

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [13]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [14]:
int_32_tensor = torch.tensor([3,6,9],dtype= torch.long,device='cuda')
int_32_tensor

tensor([3, 6, 9], device='cuda:0')

In [15]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting infomation from the tensor (Tensor attributes)

1. tensor not right dtype = to do get datatype from a tensor,can use tensor.dtype
2. tensor not right shape - to do get shape from a tensor, can use tensor.shape
3. tensor not on the right device - to do get device from a tensor, can use tensor.device

In [16]:
# create a tensor
some_tensor = torch.rand(3,4,device = 'cuda')
some_tensor

tensor([[0.0507, 0.2048, 0.8484, 0.3102],
        [0.9102, 0.9626, 0.9881, 0.7440],
        [0.8471, 0.5601, 0.0891, 0.6759]], device='cuda:0')

In [17]:
#Find out details about some tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.0507, 0.2048, 0.8484, 0.3102],
        [0.9102, 0.9626, 0.9881, 0.7440],
        [0.8471, 0.5601, 0.0891, 0.6759]], device='cuda:0')
torch.float32
torch.Size([3, 4])
cuda:0


### Manipulating Tensors (tensor operations)
Tensor operation include:
* Addition
* Substraction
* Multiplication (elements-wise)
* Division
* Matrix multiplication

In [18]:
# create a tensor
tensor = torch.tensor([1,2,3])

In [19]:
tensor + 10

tensor([11, 12, 13])

In [20]:
tensor * 10

tensor([10, 20, 30])

In [21]:
tensor

tensor([1, 2, 3])

In [22]:
tensor - 10

tensor([-9, -8, -7])

In [23]:
tensor

tensor([1, 2, 3])

In [24]:
# try out pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [25]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [26]:
### Matrix Multiplication (dot product)
print(tensor,"*",tensor)
print(f'equals:{tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [27]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [28]:
tensor

tensor([1, 2, 3])

In [29]:
# Matrix multiplication
1*1 + 2*2+3*3

14

In [30]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)    

tensor(14)
CPU times: user 944 µs, sys: 1.05 ms, total: 1.99 ms
Wall time: 2.14 ms


In [31]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 561 µs, sys: 624 µs, total: 1.19 ms
Wall time: 1.06 ms


tensor(14)

In [32]:
### one of the most common error that can occur in matrix multiplication
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.2220, 0.9543],
        [0.6749, 0.3574]])

In [33]:
# shape for matrix multiplication 
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [9,12]])

In [34]:
# torch.mm(tensor_A,tensor_B)

In [35]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [36]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  9,  9],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [37]:
tensor_B,tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [38]:
# the matrix multiplication operation works when tensor_b is transposed
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  33],
        [ 53,  67,  75],
        [ 83, 105, 117]])

In [39]:
## Finding the min,max,mean,sum etc(tensor aggregation)

In [40]:
#create a tensor
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [41]:
#Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [42]:
# Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [43]:
# find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [44]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [45]:
torch.argmin(x)

tensor(0)

In [46]:
torch.argmax(x)

tensor(9)

In [47]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
## reshaping,stacking,squeezing and unsqueezing tensor
# stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
# squeeze - removes all '1' dimensions from a tensor
# unsqueeze - add a '1' dimension to a target tensor
# permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [49]:
# lets create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# x_reshaped = x.reshape(9,1)
# x_reshaped,x_reshaped.shape

In [51]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# changing z changes x (because a view of a tensor shares the same memory as the original)

In [54]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# stacking
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [56]:
# torch.squeeze() - removes all single dimentions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
x_reshaped.shape

torch.Size([1, 9])

In [58]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
x_reshaped.squeeze().shape

torch.Size([9])

In [60]:
print(f'Previous tensor : {x_reshaped}')
print(f'Previous shape : {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [61]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [62]:
# torch.permute - rearrages the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # hight,width,color_channels

# permute the original tensor to rearrage the axis order
x_permuted = x_original.permute(2,0,1)  #shifts axis 0->1,1->2,2->0
x_permuted.shape

torch.Size([3, 224, 224])

In [63]:
x_original[0,0,0] = 728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [64]:
## indexing (selecting data from tensors)

# Indexing with pytorch is similar with Numpy

In [65]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# lets index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [68]:
# lets index on most inner bracket
x[0][0][0]

tensor(1)

In [69]:
 x[0][2][2]

tensor(9)

In [70]:
# you can also use ":" to select 'all' of a target dimensions
x[:,0]

tensor([[1, 2, 3]])

In [72]:
x[:,:,0]

tensor([[1, 4, 7]])

In [75]:
# get all values of the 0 dimension but only 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [76]:
# get index 0 of 0th and lst dimension and all values of 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

In [77]:
x[:,2,2]

tensor([9])

In [88]:
x[:,:,2]

tensor([[3, 6, 9]])

In [94]:
# pytorch tensors & numpy
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
array.dtype

dtype('float64')

In [96]:
tensor.dtype

torch.float64

In [97]:
torch.arange(1.0,8.0).dtype

torch.float32

In [98]:
# change the value of array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [100]:
numpy_tensor.dtype

dtype('float32')

In [101]:
# change the tensor, what happens to numpy_tensor
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [102]:
# reproducibility (trying to take randon out of random)
torch.rand(3,3)

tensor([[0.8395, 0.2689, 0.6693],
        [0.0626, 0.5523, 0.5466],
        [0.8429, 0.4137, 0.8631]])

In [105]:
import torch

# create two randon tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5947, 0.6654, 0.0415, 0.1187],
        [0.4798, 0.5572, 0.3723, 0.1822],
        [0.3578, 0.0872, 0.9806, 0.7125]])
tensor([[0.0735, 0.6685, 0.6519, 0.2161],
        [0.1746, 0.7879, 0.1010, 0.0122],
        [0.1125, 0.6110, 0.2755, 0.8051]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [107]:
# lets make some random but reproducible tensor

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [108]:
!nvidia-smi

Mon Feb 26 00:13:41 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.10              Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   48C    P0             24W /  130W |    1136MiB /   8188MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [109]:
import torch
torch.cuda.is_available()

True

In [112]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [113]:
# count number of device
torch.cuda.device_count()

1

In [114]:
## putting tensors (and models on the gpu)
# create a tensor (default is on cpu)
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [117]:
# move tensor to gpu (if avail)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [118]:
# Moving tensors back to the cpu
# if tensor is on gpu , can't transorm to numpy
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [119]:
# to fix the gpu tensor with numpy issue , we can first set it to cpu 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [120]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [122]:
## Excercies & Extra curriculam excercies
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [125]:
tensor_a = torch.rand(1,7)
tensor_a

tensor([[0.1716, 0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014]])

In [127]:
tensor_b = torch.rand(1,7)
tensor_b

tensor([[0.3139, 0.4654, 0.1612, 0.1568, 0.2083, 0.3289, 0.1054]])

In [129]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[0.4898]])

In [130]:
random_seed = 0
torch.manual_seed(random_seed)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [131]:
random_seed = 0
torch.manual_seed(random_seed)
tensor_a = torch.rand(1,7)
tensor_a

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [132]:
random_seed = 0
torch.manual_seed(random_seed)
tensor_b = torch.rand(1,7)
tensor_b

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [133]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[1.5985]])

In [135]:
random_seed = 0
torch.cuda.manual_seed(random_seed)
x = torch.rand(5,6)
x

tensor([[0.9298, 0.7231, 0.7423, 0.5263, 0.2437, 0.5846],
        [0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352],
        [0.2056, 0.5932, 0.1123, 0.1535, 0.2417, 0.7262],
        [0.7011, 0.2038, 0.6511, 0.7745, 0.4369, 0.5191]])

In [161]:
random_seed = 0
torch.manual_seed(random_seed)
a = torch.rand(2,3)
random_seed = 0
torch.manual_seed(random_seed)
b = torch.rand(2,3)

In [162]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [172]:
random_seed = 1234
torch.manual_seed(random_seed)
a_on_gpu = a.to(device)
random_seed = 1234
torch.manual_seed(random_seed)
b_on_gpu = b.to(device)
a_on_gpu,b_on_gpu

(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]], device='cuda:0'),
 tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]], device='cuda:0'))

In [180]:
multiplication = torch.matmul(a_on_gpu,b_on_gpu.T)
multiplication

tensor([[0.8443, 0.3578],
        [0.3578, 0.5140]], device='cuda:0')

In [200]:
torch.max(multiplication),multiplication[0,0]

(tensor(0.8443, device='cuda:0'), tensor(0.8443, device='cuda:0'))

In [199]:
torch.min(multiplication),multiplication[1,0]

(tensor(0.3578, device='cuda:0'), tensor(0.3578, device='cuda:0'))

In [206]:
random_seed = 7
torch.manual_seed(random_seed)
random_tensor = torch.rand(1,1,1,10)
random_tensor,random_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [207]:
x = random_tensor.squeeze()
x.shape

torch.Size([10])